name: Build and Push container images

on:
  workflow_dispatch:

jobs:

  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }} # This jobs output will be named as (changes)
    steps:
      - name: Checkout code # placed before filter, coz filter runs git commands, so without checkout there might not be proper repo metadata
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # checkouts entire repo, all branches, all tags, etc.. (without this the defult would be -> 1 [which checkouts only the latest commits])
        
      - name: filter
        id: filter
        uses: dorny/paths-filter@v3 # It checks which files/folders changed in a commit or PR.
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # for dorny to access gihtub api
          base: main
          filters: .github/utils/file-filters.yaml

  build-push-container-images:
    runs-on: ubuntu-24.04
    needs: filter
    strategy:
      fail-fast: false
      matrix:
        service: ${{fromJson(needs.filter.output.services)}}

    steps:
      - name: checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          fetch-depth: 0 # complete repo will be checkouted
          
      - name: Install Task CLI
        uses: go-task/setup-task@v1
        with:
          version: 3.44.1

      - name: Auth to dockerhub
        if: ${{!env.ACT}} # if not running on act, authenticate
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU # tool that lets you run programs built for one CPU architecture on another.
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx # lets you build multi-arch images
        uses: docker/setup-buildx-action@v3

      - name: Compute Image tags
        id: image-tag
        run: |
          version=foo
          image_tag=foobar
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "image_tag=${image_tag}" >> $GITHUB_OUTPUT
      
      - name: Build and Push image
        uses: docker/build-push-action@v7
        with:
          context: ${{matrix.service}}
          push: ${{!env.ACT}} # if it is not running on act, push it
          tags: ${{steps.image-tag.outputs.image_tag}}
          platforms: linux/amd64,linux/arm64 # builds these images
          cache-from: type=gha
          cache-to: type=gha,mode=max